version: '3.8'

services:
  walkies-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walkies
    volumes:
      - walkies-db-data:/var/lib/postgresql/data

volumes:
  walkies-db-data:
    driver: local
